# 改配置配置只对 嵌入式容器、Spring、Hibernate生效
debug: false

logging:
  level:
    # org.springframework.web目录下日志级别debug
    org.springframework.web: debug
    # com.mkeeper目录下日志级别info
    com.mkeeper: info
    # com.mkeeper.controller.off目录下日志关闭
    com.mkeeper.controller.off: off

# 颜色日志配置
spring:
  output:
    ansi:
      enabled: detect




