apache:
  rocketmq:
    #消费者的组名
    consumer:
      PushConsumer: PushConsumer
    # 生产者的组名
    producer:
      producerGroup: Producer
    # NameServer地址
    namesrvAddr: 192.168.162.129:9876
debug: true
logging:
  level: debug
