elastic-job:
  serverLists: 127.0.0.1:2181
  namespace: elastic-job

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.mkeeper.model
